/** Incident Portfolio / Digital Twin revision. Tell the assistant “回退到 DTn” to restore. */
export const DIGITAL_TWIN_VERSION = "DT37"

export const DIGITAL_TWIN_REVISION_LOG = [
  { id: "DT1", note: "浅色 SVG 流程图" },
  { id: "DT2", note: "深色科技风 2.5D，等距方块 + 动线" },
  { id: "DT3", note: "Three.js 立柱三维场景" },
  { id: "DT4", note: "浅色二维分区拓扑，无动线" },
  { id: "DT5", note: "深色科技风 + 二维设备图标 + 动线（动线在图层下方）" },
  { id: "DT6", note: "DT5 基础上将动线提到最前层" },
  { id: "DT7", note: "报警级别配色固定：P1 红 / P2 橙；不再随场景域颜色变化" },
  { id: "DT8", note: "Recommended Actions 当前场景卡片高亮加强（色条 + CURRENT 标签 + 其余降对比）" },
  { id: "DT9", note: "菜单改为自动分析；去掉本页回答；告警收敛漏斗改为左右分列清单" },
  { id: "DT10", note: "收敛漏斗：左全量告警 / 中规则下拉聚合 / 右最终根因；四场景告警时序与角色对齐" },
  { id: "DT11", note: "告警收敛改为可解释流图：Sankey + Top3 规则展开 + 多对一归并 + Explain Why 证据" },
  { id: "DT12", note: "收敛数字可下钻：右侧抽屉追溯 Raw / 聚合组 / 规则详情 / Explain Why 证据树" },
  { id: "DT13", note: "Alarm Convergence Workspace：横向 Pulse Flow + 页内 Event Grid + 规则下移，去掉抽屉" },
  { id: "DT14", note: "事件列表与 Affected Events 增加白话说明，方便非专业人士理解告警码" },
  { id: "DT15", note: "影响链路改为数字孪生图叠加：同风格拓扑上标记根因、受影响节点与传播路径" },
  { id: "DT16", note: "RCA 顶部融合为 Incident Overview：KPI + 传播链 + 证据卡 + 事故故事时间线" },
  { id: "DT17", note: "根因路径恢复数字孪生叠加风格：跳数条 + 拓扑标注传播链路" },
  { id: "DT18", note: "去掉路径跳数框图；Overview 拆成根因汇总+建议行动；故事时间线提前" },
  { id: "DT19", note: "RCA 信息只出现一次：KPI 结论、可视化故事、Flow 贡献度、Rules 去事件列表" },
  { id: "DT20", note: "点 Flow 同时联动规则详情；去掉独立 Convergence Rules 区块" },
  { id: "DT21", note: "去掉 Rule Detail；页面双语标题统一为中文为主、英文为辅" },
  { id: "DT22", note: "人工调查改为调查员工作台：事件确认、候选、影响、时间线、设备证据、原始告警、排查路径" },
  { id: "DT23", note: "人工调查按 Detect / Impact / Locate / Cause 组织，影响与定位复用首页数字孪生" },
  { id: "DT24", note: "人工调查全量事件清单、规则聚合预览与独立 AI Chat 对话框，不受 Demo Scenario 切换" },
  { id: "DT25", note: "人工调查顶部全量数字孪生 + 原始告警清单；点选告警标注位置与可能影响路径" },
  { id: "DT26", note: "人工调查孪生图去掉域事故聚合标注；AI 分析探索固定为页内联动对话" },
  { id: "DT27", note: "人工调查原始告警增加时间范围过滤，并支持勾选批次后预览收敛效果" },
  { id: "DT28", note: "人工调查 Batch Convergence 改为策略模拟器：漏斗、四策略对比、规则贡献与告警血缘" },
  { id: "DT29", note: "收敛模拟器内置降噪/关系/场景管道，勾选方法后按固定路径给出所选收敛效果" },
  { id: "DT30", note: "收敛管道改为自上而下流程图：分叉汇聚、步骤编号与白话说明" },
  { id: "DT31", note: "流程图流动线减半；规则贡献改为按分支讲识别结果，不再用 Input/Output 表" },
  { id: "DT32", note: "规则识别展开改为事件明细表，同设备用稳定色条分组便于核对震荡/重复" },
  { id: "DT33", note: "流程图亮色流动线速度降至约 1/4，便于顺着路径看" },
  { id: "DT34", note: "人工调查去掉发现问题、理解影响两个模块" },
  { id: "DT35", note: "人工调查 AI 分析探索支持左右展开 / 收起" },
  { id: "DT36", note: "RCA 顶部 Root Cause First：固定 Incident Decision Banner + Evidence Chips + 证据链展开" },
  { id: "DT37", note: "一级菜单改为事故中心 / 事故工作台 / 调查工作台；删除 AI 推理中心" },
] as const
