/** Incident Portfolio / Digital Twin revision. Tell the assistant “回退到 DTn” to restore. */
export const DIGITAL_TWIN_VERSION = "DT57"

export const DIGITAL_TWIN_REVISION_LOG = [
  { id: "DT1", note: "浅色 SVG 流程图" },
  { id: "DT2", note: "深色科技风 2.5D，等距方块 + 动线" },
  { id: "DT3", note: "Three.js 立柱三维场景" },
  { id: "DT4", note: "浅色二维分区拓扑，无动线" },
  { id: "DT5", note: "深色科技风 + 二维设备图标 + 动线（动线在图层下方）" },
  { id: "DT6", note: "DT5 基础上将动线提到最前层" },
  { id: "DT7", note: "报警级别配色固定：P1 红 / P2 橙；不再随场景域颜色变化" },
  { id: "DT8", note: "Recommended Actions 当前场景卡片高亮加强（色条 + CURRENT 标签 + 其余降对比）" },
  { id: "DT9", note: "菜单改为自动分析；去掉本页回答；告警收敛漏斗改为左右分列清单" },
  { id: "DT10", note: "收敛漏斗：左全量告警 / 中规则下拉聚合 / 右最终根因；四场景告警时序与角色对齐" },
  { id: "DT11", note: "告警收敛改为可解释流图：Sankey + Top3 规则展开 + 多对一归并 + Explain Why 证据" },
  { id: "DT12", note: "收敛数字可下钻：右侧抽屉追溯 Raw / 聚合组 / 规则详情 / Explain Why 证据树" },
  { id: "DT13", note: "Alarm Convergence Workspace：横向 Pulse Flow + 页内 Event Grid + 规则下移，去掉抽屉" },
  { id: "DT14", note: "事件列表与 Affected Events 增加白话说明，方便非专业人士理解告警码" },
  { id: "DT15", note: "影响链路改为数字孪生图叠加：同风格拓扑上标记根因、受影响节点与传播路径" },
  { id: "DT16", note: "RCA 顶部融合为 Incident Overview：KPI + 传播链 + 证据卡 + 事故故事时间线" },
  { id: "DT17", note: "根因路径恢复数字孪生叠加风格：跳数条 + 拓扑标注传播链路" },
  { id: "DT18", note: "去掉路径跳数框图；Overview 拆成根因汇总+建议行动；故事时间线提前" },
  { id: "DT19", note: "RCA 信息只出现一次：KPI 结论、可视化故事、Flow 贡献度、Rules 去事件列表" },
  { id: "DT20", note: "点 Flow 同时联动规则详情；去掉独立 Convergence Rules 区块" },
  { id: "DT21", note: "去掉 Rule Detail；页面双语标题统一为中文为主、英文为辅" },
  { id: "DT22", note: "人工调查改为调查员工作台：事件确认、候选、影响、时间线、设备证据、原始告警、排查路径" },
  { id: "DT23", note: "人工调查按 Detect / Impact / Locate / Cause 组织，影响与定位复用首页数字孪生" },
  { id: "DT24", note: "人工调查全量事件清单、规则聚合预览与独立 AI Chat 对话框，不受 Demo Scenario 切换" },
  { id: "DT25", note: "人工调查顶部全量数字孪生 + 原始告警清单；点选告警标注位置与可能影响路径" },
  { id: "DT26", note: "人工调查孪生图去掉域事故聚合标注；AI 分析探索固定为页内联动对话" },
  { id: "DT27", note: "人工调查原始告警增加时间范围过滤，并支持勾选批次后预览收敛效果" },
  { id: "DT28", note: "人工调查 Batch Convergence 改为策略模拟器：漏斗、四策略对比、规则贡献与告警血缘" },
  { id: "DT29", note: "收敛模拟器内置降噪/关系/场景管道，勾选方法后按固定路径给出所选收敛效果" },
  { id: "DT30", note: "收敛管道改为自上而下流程图：分叉汇聚、步骤编号与白话说明" },
  { id: "DT31", note: "流程图流动线减半；规则贡献改为按分支讲识别结果，不再用 Input/Output 表" },
  { id: "DT32", note: "规则识别展开改为事件明细表，同设备用稳定色条分组便于核对震荡/重复" },
  { id: "DT33", note: "流程图亮色流动线速度降至约 1/4，便于顺着路径看" },
  { id: "DT34", note: "人工调查去掉发现问题、理解影响两个模块" },
  { id: "DT35", note: "人工调查 AI 分析探索支持左右展开 / 收起" },
  { id: "DT36", note: "RCA 顶部 Root Cause First：固定 Incident Decision Banner + Evidence Chips + 证据链展开" },
  { id: "DT37", note: "一级菜单改为事故中心 / 事故工作台 / 调查工作台；删除 AI 推理中心" },
  { id: "DT38", note: "事故选择器仅出现在事故工作台，事故中心与调查工作台内容不受其控制" },
  { id: "DT39", note: "一级菜单改为事故中心 / 事件调查中心；事故总览与事故工作台降为事故中心子菜单" },
  { id: "DT40", note: "事故总览数字孪生下移缩小；Impact/Power/Cooling/Network 标签；默认只高亮根因与受影响对象，放大后展示机架与设备名" },
  { id: "DT41", note: "事故总览重构为 L0 指挥摘要 / L1 事故列表 / L2 故事与证据 / L3 影响恢复 / L4 三栏行动，数字孪生跟随所选事故" },
  { id: "DT42", note: "事故总览去重：L0 只保留摘要与恢复时间轴，L3 改为影响拆解与传播链，L4 改名为执行中心并作为 Action 详情唯一入口" },
  { id: "DT43", note: "取消 Execution Center；L0 仅当前事故视角；执行信息并入 Incident Portfolio 事故卡" },
  { id: "DT44", note: "事故组合左栏卡片；右侧事故详情（行动/故事/证据/影响）默认收起，选中后以强调底色成组展示" },
  { id: "DT45", note: "数字孪生从事故总览拆出为事故中心三级菜单；总览只回答发生了什么，孪生负责位置与传播解释" },
  { id: "DT46", note: "事故总览底部恢复压缩版数字孪生；独立数字孪生视图保持不变" },
  { id: "DT47", note: "事故总览改为 Portfolio First：顶部全局态势，40/60 Master-Detail，单事故信息仅在右侧详情" },
  { id: "DT48", note: "事故卡片改为 3 秒可读结构：生命周期状态、Open/Recovery/Impact、Action Status，去掉评分与双重进度" },
  { id: "DT49", note: "Portfolio 只保留导航字段；Owner/Action/ETA 仅出现在右侧 Detail" },
  { id: "DT50", note: "数字孪生视图去掉本页回答模块" },
  { id: "DT51", note: "数字孪生改为 L1 事故 / L2 视图 / L3 叠加三层结构，不再并列" },
  { id: "DT52", note: "去掉侧栏路径标注；画布标题改为 Digital Twin Canvas；三层标签去掉问题句" },
  { id: "DT53", note: "顶栏事故选择器下移到事故工作台，与数字孪生共用同一套事故芯片" },
  { id: "DT54", note: "事故摘要增加开始/更新时间；详情可跳转工作台并带上所选事故" },
  { id: "DT55", note: "总览只保留导航与摘要；工作台承接故事/证据/影响，并新增根因分析重点区" },
  { id: "DT56", note: "工作台按 What → Why → Impact → Action → Evidence 重组；告警收敛迁到调查中心" },
  { id: "DT57", note: "工作台改为左侧旅程导航 + 右侧章节，默认只展开 Summary / Root Cause" },
] as const
